services:
  # 1. Il Service Registry
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8761/"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - smart-charging-network

  # 2. L'API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 3. Il Tariff Provider
  tariff-provider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: tariff-provider
    container_name: tariff-provider
    ports:
      - "8081:8081" # Esponiamo la porta per testare Swagger dal Mac
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 4. Lo Station Provider
  station-provider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: station-provider
    container_name: station-provider
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 5. Il Vehicle Provider
  vehicle-provider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: vehicle-provider
    container_name: vehicle-provider
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 6. L'Energy Prosumer
  energy-prosumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: energy-prosumer
    container_name: energy-prosumer
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 7. Il Charging Orchestrator
  charging-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: charging-orchestrator
    container_name: charging-orchestrator
    ports:
      - "8085:8085"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - smart-charging-network

  # 8. Frontend UI Vue
  frontend-ui:
    build:
      context: ./frontend-ui
    container_name: frontend-ui
    ports:
      - "8080:80"
    networks:
      - smart-charging-network

networks:
  smart-charging-network:
    driver: bridge