server:
  port: 8081 # Porta locale dedicata al Tariff Provider

spring:
  application:
    name: tariff-provider # Nome con cui verrà registrato su Eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ # Usa il nome del container, non localhost